version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  go_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_go_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
